### ISSUE TITLE
云函数报错No module named 'schedule'

### ISSUE THREAD

**Issue by cappuccinokm** [Xm798/Genshin-Dailynote-Helper#17]
### 问题描述

腾讯云函数，试过了配置 cloud 和 local 都是报这一个错误，
本地用python跑起来没问题

### 运行环境

云函数

### 程序版本

2.1.4

### 完整日志

```shell
START RequestId: f1b93b94-51d1-4c18-91dc-3724f6d0a4a1

Init Report RequestId: f1b93b94-51d1-4c18-91dc-3724f6d0a4a1 Coldstart: 253ms (PullCode: 10ms InitRuntime: 7ms InitFunction: 236ms) Memory: 64MB MemUsage: 8.06MB

ERROR RequestId: f1b93b94-51d1-4c18-91dc-3724f6d0a4a1 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python37/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python37/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python37/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python37/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 728, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/user/index.py", line 1, in <module>     from dailynotehelper import run   File "/var/user/dailynotehelper/__init__.py", line 1, in <module>     import schedule ModuleNotFoundError: No module named 'schedule'", "statusCode": 443}

END RequestId: f1b93b94-51d1-4c18-91dc-3724f6d0a4a1

Report RequestId: f1b93b94-51d1-4c18-91dc-3724f6d0a4a1 Duration: 0ms Memory: 64MB MemUsage: 8.06MB
```

**Comment by Xm798** [comment]
使用当前 2.1.4 的包在云函数部署，运行正常，无法复现该 bug。建议重新下载 2.1.4 的zip包部署尝试一下？检查包里有没有 schedule 文件夹，不要修改里面的东西，下载下来直接上传。

```
START RequestId: 7891482d-b7d8-4842-b2f0-c464923e6465
Init Report RequestId: 7891482d-b7d8-4842-b2f0-c464923e6465 Coldstart: 1209ms (PullCode: 58ms InitRuntime: 15ms InitFunction: 1136ms) Memory: 128MB MemUsage: 21.11MB
-------------------------------------------------------------
|                Genshin Dailynote Helper                   |
-------------------------------------------------------------
| Current Version: 2.1.4                                    |
| Last Update: Feb 16, 2022                                 |
| Github: https://github.com/Xm798/Genshin-Dailynote-Helper |
-------------------------------------------------------------
🗝️ 目前配置了1個帳號，正在執行第1個
-------------------------
正在獲取角色資料
Starting new HTTPS connection (1): api-takumi.mihoyo.com:443
https://api-takumi.mihoyo.com:443 "GET /binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn HTTP/1.1" 200 369
獲取到國服的2個角色...
第1個角色，1xxxxxxx6 xxx
Starting new HTTPS connection (1): api-takumi-record.mihoyo.com:443
https://api-takumi-record.mihoyo.com:443 "GET /game_record/app/genshin/api/dailyNote?role_id=1xxxxxx6&server=cn_gf01 HTTP/1.1" 200 1221
⏩︎未到每日委託檢查提醒時間。
🔔樹脂已到臨界值，當前樹脂116，發送提醒。
✅洞天寶錢檢查結束，未溢出。
🔔有已完成的探索派遣，發送提醒。
Starting new HTTPS connection (1): telegramapi.xm.mk:443
https://telegramapi.xm.mk:443 "POST /bot1626318709:AAFxirkn0UexwvzyA9r74R_KLnfbWfKQUHU/sendMessage HTTP/1.1" 200 None
Telegram Bot 🥳
-------------------------
第2個角色，xxxxxxx 旅行者
跳過該角色
-------------------------
本輪執行結束，等待下次檢查...
Response RequestId:7891482d-b7d8-4842-b2f0-c464923e6465 RetMsg:null
END RequestId:7891482d-b7d8-4842-b2f0-c464923e6465
Report RequestId:7891482d-b7d8-4842-b2f0-c464923e6465 Duration:3384ms Memory:128MB MemUsage:22.687500MB
```

**Comment by cappuccinokm** [comment]
后面尝试中已解决，谢谢解答
