### ISSUE TITLE
国际服报错

### ISSUE THREAD

**Issue by stevened7246** [Xm798/Genshin-Dailynote-Helper#28]
### 问题描述

大佬幫幫我~

### 运行环境

Docker

### 程序版本

2.1.7.2

### 完整日志

```shell
2022-04-29 01:18:27 INFO
-------------------------------------------------------------

|                Genshin Dailynote Helper                   |
-------------------------------------------------------------
| Current Version: 2.1.7.2                                  |
| Last Update: Apr 27, 2022                                 |
| Github: https://github.com/Xm798/Genshin-Dailynote-Helper |
-------------------------------------------------------------

2022-04-29 01:18:27 INFO 🗝️ 当前配置了1个账号，正在执行第1个
2022-04-29 01:18:27 INFO -------------------------
2022-04-29 01:18:27 INFO 正在获取角色信息
2022-04-29 01:18:28 INFO 获取到国际服的2个角色...
2022-04-29 01:18:28 INFO 第1个角色，618705912 玩家618705912
2022-04-29 01:18:28 INFO 跳过该角色
2022-04-29 01:18:28 INFO 第2个角色，900545313 輕若羽雨
Traceback (most recent call last):
  File "./index.py", line 3, in <module>
    run()
  File "/app/dailynotehelper/__init__.py", line 203, in run
    run_once()
  File "/app/dailynotehelper/__init__.py", line 197, in run_once
    start(config.COOKIE_HOYOLAB, 'os')
  File "/app/dailynotehelper/__init__.py", line 173, in start
    dailynote_info, message = client.prase_dailynote_info(role)
  File "/app/dailynotehelper/getinfo/client.py", line 84, in prase_dailynote_info
    prase_info(self.dailynote_info, role) if self.dailynote_info else ''
  File "/app/dailynotehelper/getinfo/praseinfo.py", line 22, in prase_info
    result.append(f"{role['nickname']} {server[role['region']]}")
KeyError: 'os_cht'
```

**Comment by Xm798** [comment]
这是港澳台服？

**Comment by stevened7246** [comment]
> 这是港澳台服？

对的

**Comment by Xm798** [comment]
是 bug，忘记处理台港澳服了。docker 正由 [Action 自动构建中](https://github.com/Xm798/Genshin-Dailynote-Helper/actions/runs/2249573582)，等构建完成后拉取 latest 镜像运行即可。

**Comment by stevened7246** [comment]
> 是 bug，忘记处理台港澳服了。docker 正由 [Action 自动构建中](https://github.com/Xm798/Genshin-Dailynote-Helper/actions/runs/2249573582)，等构建完成后拉取 latest 镜像运行即可。

感谢~

**Comment by Xm798** [comment]
感谢发现bug，我自己国际服的号还是因为这个项目专门去某宝搞了个亚服小号，漏掉了还有台港澳服这件事……昨天太忙忘记处理issue了🤣

**Comment by stevened7246** [comment]
新bug
```shell
Traceback (most recent call last):
  File "./index.py", line 3, in <module>
    run()
  File "/app/dailynotehelper/__init__.py", line 203, in run
    run_once()
  File "/app/dailynotehelper/__init__.py", line 197, in run_once
    start(config.COOKIE_HOYOLAB, 'os')
  File "/app/dailynotehelper/__init__.py", line 175, in start
    check(role['region'], dailynote_info, message)
  File "/app/dailynotehelper/__init__.py", line 28, in check
    time_delta = reset_time_offset(region)
  File "/app/dailynotehelper/utils.py", line 72, in reset_time_offset
    delta = -tz_diff(tz_server[region], tz_local) - 4
KeyError: 'os_cht'
```

**Comment by Xm798** [comment]
> 新bug
> 
> ```shell
> Traceback (most recent call last):
>   File "./index.py", line 3, in <module>
>     run()
>   File "/app/dailynotehelper/__init__.py", line 203, in run
>     run_once()
>   File "/app/dailynotehelper/__init__.py", line 197, in run_once
>     start(config.COOKIE_HOYOLAB, 'os')
>   File "/app/dailynotehelper/__init__.py", line 175, in start
>     check(role['region'], dailynote_info, message)
>   File "/app/dailynotehelper/__init__.py", line 28, in check
>     time_delta = reset_time_offset(region)
>   File "/app/dailynotehelper/utils.py", line 72, in reset_time_offset
>     delta = -tz_diff(tz_server[region], tz_local) - 4
> KeyError: 'os_cht'
> ```

寄…

 28a36d23d05de2ef13426fe1f272bbe531996706  fixed

**Comment by Xm798** [comment]
docker 覆盖了 latest 和 v2.1.7.4，重新拉一下试一下……

**Comment by stevened7246** [comment]
> docker 覆盖了 latest 和 v2.1.7.4，重新拉一下试一下……

完美~
