### ISSUE TITLE
洞天宝钱奇怪溢出

### ISSUE THREAD

**Issue by stevened7246** [Xm798/Genshin-Dailynote-Helper#29]
### 问题描述

bug+1？

### 运行环境

Docker

### 程序版本

2.1.7.4

### 完整日志

```shell
2022-05-01 01:09:01 INFO 🗝️ 目前配置了1個帳號，正在執行第1個
2022-05-01 01:09:01 INFO -------------------------
2022-05-01 01:09:01 INFO 正在獲取角色資料
2022-05-01 01:09:02 INFO 獲取到國際服的2個角色...
2022-05-01 01:09:02 INFO 第1個角色，618705912 玩家618705912
2022-05-01 01:09:02 INFO 跳過該角色
2022-05-01 01:09:02 INFO 第2個角色，900545313 輕若羽雨
Traceback (most recent call last):
  File "./index.py", line 3, in <module>
    run()
  File "/app/dailynotehelper/__init__.py", line 206, in run
    schedule.run_pending()
  File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/app/dailynotehelper/__init__.py", line 197, in run_once
    start(config.COOKIE_HOYOLAB, 'os')
  File "/app/dailynotehelper/__init__.py", line 173, in start
    dailynote_info, message = client.prase_dailynote_info(role)
  File "/app/dailynotehelper/getinfo/client.py", line 81, in prase_dailynote_info
    self._get_dailynote_info(role['game_uid'], role['region'])
  File "/app/dailynotehelper/getinfo/client.py", line 68, in _get_dailynote_info
    self.dailynote_info = BaseData.parse_obj(response.data)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for BaseData
transformer
  none is not an allowed value (type=type_error.none.not_allowed)
2022-05-01 01:09:04 INFO
-------------------------------------------------------------
|                Genshin Dailynote Helper                   |
-------------------------------------------------------------
| Current Version: v2.1.7.4                                 |
| Last Update: Apr 30, 2022                                 |
| Github: https://github.com/Xm798/Genshin-Dailynote-Helper |
-------------------------------------------------------------

2022-05-01 01:09:04 INFO 🗝️ 目前配置了1個帳號，正在執行第1個
2022-05-01 01:09:04 INFO -------------------------
2022-05-01 01:09:04 INFO 正在獲取角色資料
2022-05-01 01:09:04 INFO 獲取到國際服的2個角色...
2022-05-01 01:09:04 INFO 第1個角色，618705912 玩家618705912
2022-05-01 01:09:04 INFO 跳過該角色
2022-05-01 01:09:04 INFO 第2個角色，900545313 輕若羽雨
2022-05-01 01:09:05 INFO ✅ 委託檢查結束，今日委託已完成，獎勵已領取。
2022-05-01 01:09:05 INFO ✅樹脂檢查結束，當前樹脂60，未到提醒臨界值。
2022-05-01 01:09:05 INFO 🔔洞天寶錢已到臨界值，發送提醒。
2022-05-01 01:09:05 INFO ✅探索派遣檢查結束，不存在完成的探索派遣。
2022-05-01 01:09:05 INFO ⏩︎參數質變儀未獲得。
2022-05-01 01:09:05 ERROR Discord 😳
[Errno Expecting value] : 0
2022-05-01 01:09:05 INFO -------------------------
2022-05-01 01:09:05 INFO 本輪執行結束，等待下次檢查...
```

### 其他补充说明

对的是我，我又来了（bushi）
在某些时刻会突然显示钱钱满惹（应该是随机）

**Comment by Xm798** [comment]
啊这 奇奇怪怪捏 明天起来看看😭

**Comment by stevened7246** [comment]
> 啊这 奇奇怪怪捏 明天起来看看😭

早点睡~

**Comment by Xm798** [comment]
看 log 应该是米游社接口没有返回参量质变仪的数据……没看出洞天宝钱有什么异常…
提示的时候洞天宝钱的值是多少捏？有没有超过阈值×最大值呢
我今天用postman调hoyolab接口的时候也出现了有时候没参量质变仪数据的问题，奇奇怪怪的

**Comment by stevened7246** [comment]
> 看 log 应该是米游社接口没有返回参量质变仪的数据……没看出洞天宝钱有什么异常… 提示的时候洞天宝钱的值是多少捏？有没有超过阈值×最大值呢 我今天用postman调hoyolab接口的时候也出现了有时候没参量质变仪数据的问题，奇奇怪怪的

错误的时候倒是不知道，但是刚领完有一段时间便签显示只有32不可能到上限
而且也是一长串中间报错然后重新开始？
话说阈值应该是百分比吧？0.9=90%？我是填的0.95
如果长时间没好可以加个使用上次数据推算？

**Comment by Xm798** [comment]
1. 异常崩溃退出是国际服接口的原因，有不小的概率会返回一个null的参量质变仪信息导致程序退出，这个问题修复了。
2. 阈值是百分比没错的，没有定位到推送错误的原因，但我在 v2.1.7.4_fix 中加了打印接口原始返回信息和当前的宝钱信息，这个请您拉一下最新的镜像（v2.1.7.4_fix），再观察一下，还有问题的话，贴一下log我再看看。
3. 推算比较难实现，因为这个项目更多的用户是用云函数（serverless）来运行的，云函数无法持久化保存数据。定位到问题原因再看吧
4. 意外发现了 discord 推送状态检测错误的 bug，顺手修复了。

**Comment by stevened7246** [comment]
> 



> 1. 异常崩溃退出是国际服接口的原因，有不小的概率会返回一个null的参量质变仪信息导致程序退出，这个问题修复了。
> 2. 阈值是百分比没错的，没有定位到推送错误的原因，但我在 v2.1.7.4_fix 中加了打印接口原始返回信息和当前的宝钱信息，这个请您拉一下最新的镜像（v2.1.7.4_fix），再观察一下，还有问题的话，贴一下log我再看看。
> 3. 推算比较难实现，因为这个项目更多的用户是用云函数（serverless）来运行的，云函数无法持久化保存数据。定位到问题原因再看吧
> 4. 意外发现了 discord 推送状态检测错误的 bug，顺手修复了。

应该是米哈游的问题，当时我看hoyolab也是满的状态
```
2022-05-02 01:32:41 INFO 🗝️ 目前配置了1個帳號，正在執行第1個
2022-05-02 01:32:41 INFO -------------------------
2022-05-02 01:32:41 INFO 正在獲取角色資料
2022-05-02 01:32:42 INFO 獲取到國際服的2個角色...
2022-05-02 01:32:42 INFO 第1個角色，618705912 玩家618705912
2022-05-02 01:32:42 INFO 跳過該角色
2022-05-02 01:32:42 INFO 第2個角色，900545313 輕若羽雨
2022-05-02 01:32:42 INFO {"retcode":0,"message":"OK","data":{"current_resin":100,"max_resin":160,"resin_recovery_time":"28703","finished_task_num":4,"total_task_num":4,"is_extra_task_reward_received":true,"remain_resin_discount_num":0,"resin_discount_num_limit":3,"current_expedition_num":5,"max_expedition_num":5,"expeditions":[{"avatar_side_icon":"https://upload-os-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Fischl.png","status":"Ongoing","remained_time":"15814"},{"avatar_side_icon":"https://upload-os-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Lisa.png","status":"Ongoing","remained_time":"45254"},{"avatar_side_icon":"https://upload-os-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Bennett.png","status":"Ongoing","remained_time":"15814"},{"avatar_side_icon":"https://upload-os-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Chongyun.png","status":"Ongoing","remained_time":"15814"},{"avatar_side_icon":"https://upload-os-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Sara.png","status":"Ongoing","remained_time":"15814"}],"current_home_coin":300,"max_home_coin":300,"home_coin_recovery_time":"0","calendar_url":"","transformer":{"obtained":false,"recovery_time":{"Day":0,"Hour":0,"Minute":0,"Second":0,"reached":true},"wiki":""}}}
2022-05-02 01:32:42 INFO ✅ 委託檢查結束，今日委託已完成，獎勵已領取。
2022-05-02 01:32:42 INFO ✅樹脂檢查結束，當前樹脂100，未到提醒臨界值。
2022-05-02 01:32:42 INFO 🔔当前洞天寶錢300，已到臨界值285.0，發送提醒。
2022-05-02 01:32:42 INFO ✅探索派遣檢查結束，不存在完成的探索派遣。
2022-05-02 01:32:42 INFO ⏩︎未獲得參數質變儀。
2022-05-02 01:32:42 INFO Discord 🥳
2022-05-02 01:32:42 INFO -------------------------
2022-05-02 01:32:42 INFO 本輪執行結束，等待下次檢查...
```
![Screenshot_20220502-013636528_1](https://user-images.githubusercontent.com/97885306/166234326-af109448-295e-4ae8-838c-9d97d5ea3f68.jpg)
![Screenshot_20220502-013621551](https://user-images.githubusercontent.com/97885306/166234329-3b148cc6-9af2-47f8-95fd-a7c60a16748f.jpg)

**Comment by Xm798** [comment]
好耶~最大300满的太快了哈哈哈 可惜现在壶在维护（不知道国际服是不是也在维护）没办法快速提仙力

那我就把这个版本推成正式release了 感谢反馈~
